name: Build using Docker

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write   # needed for creating a release
  packages: write   # needed for pushing to GHCR

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-dev
  IMAGE_TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.IMAGE_NAME }}
          push: always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    container:
      image: ghcr.io/${{ github.repository }}-dev
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: CMake Configure (ubuntu-release)
      run: |
        cmake --preset ubuntu-release
        
    - name: CMake Build (ubuntu-release)
      run: |
        cmake --build build --parallel $(nproc)

    - name: CPack (ubuntu-release)
      run: |
        cpack --preset ubuntu-release --verbose
